sudo: false

language: java

jdk:
  - openjdk8
 
notifications:
  email:
    recipients:
      - admin@amitinside.com
    on_success: never
    on_failure: always

install: ./gradlew --version

before_script: ./gradlew --no-daemon --version

script: ./gradlew --no-daemon --continue :build
